### PR TITLE
chore: #1: Add azure pipeline file to run tests in devops.

### PR DESCRIPTION
**Pull request by zabeen**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
fyi: Tested on dev ops and it's working

> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5#-:-Npyq0gf38TNTtG0UkSN:b-x8liml)* status: 0 of 2 files reviewed, all discussions resolved

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`test-pipeline.yml` line 1 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5#-Npyw57g3GsZSxDnsj55:-Npyw57g3GsZSxDnsj56:bb2zam3) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/d4c172b7a974659e0b3a61e0f8996adbd0c507ef/test-pipeline.yml#L1)):*
> ```YAML
> trigger: none
> ```

Could you please check the pipeline for Forms tests, i.e. - we have multi-stage process - build first (once), and then run of tests in parallel

https://github.com/Anthony-Nolan/Nova.Forms.Auto.Tests/blob/develop/azure-pipelines.yml
https://github.com/Anthony-Nolan/Nova.Forms.Auto.Tests/blob/develop/azure-test-run-template.yml

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @zabeen)

___
*[`test-pipeline.yml` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5#-NpywO4B4xgBP_uM-qUN:-NpywO4B4xgBP_uM-qUO:b-98itbz) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/d4c172b7a974659e0b3a61e0f8996adbd0c507ef/test-pipeline.yml#L4)):*
> ```YAML
> 
> schedules:
>   - cron: "0 3 * * *"
> ```

Let's not add any triggers here, we'll specify them in the Azure DevOps portal.
As the schedule will be different for different environments, i.e. you probably need to run tests dail for UAT

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`test-pipeline.yml` line 1 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5#-Npyw57g3GsZSxDnsj55:-Npz-IgT7vzSrcoPXDX6:b-pckiu1) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/d4c172b7a974659e0b3a61e0f8996adbd0c507ef/test-pipeline.yml#L1)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Could you please check the pipeline for Forms tests, i.e. - we have multi-stage process - build first (once), and then run of tests in parallel

https://github.com/Anthony-Nolan/Nova.Forms.Auto.Tests/blob/develop/azure-pipelines.yml
https://github.com/Anthony-Nolan/Nova.Forms.Auto.Tests/blob/develop/azure-test-run-template.yml
</blockquote></details>

The forms-style split pipeline seems too complex to implement at this stage when we only have an initial set of tests.

Could we create a task to enhance the pipeline once we have a workflow to execute?
___
*[`test-pipeline.yml` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5#-NpywO4B4xgBP_uM-qUN:-NpzFH-MDpumeVTptD-R:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/d4c172b7a974659e0b3a61e0f8996adbd0c507ef/test-pipeline.yml#L4)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's not add any triggers here, we'll specify them in the Azure DevOps portal.
As the schedule will be different for different environments, i.e. you probably need to run tests dail for UAT
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zabeen)

___
*[`test-pipeline.yml` line 1 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5#-Npyw57g3GsZSxDnsj55:-NpzLmBiCSFqa3kuy8sb:bav4faf) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/d4c172b7a974659e0b3a61e0f8996adbd0c507ef/test-pipeline.yml#L1)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

The forms-style split pipeline seems too complex to implement at this stage when we only have an initial set of tests.

Could we create a task to enhance the pipeline once we have a workflow to execute?
</blockquote></details>

Ok, let's have a separate subtask for that.
I'll add one more for the reporting - as it would be good to have HTML reports generated to be able to understand which steps of the test have passed, and at which step we have failed

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zabeen)

___
*[`test-pipeline.yml` line 1 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/5#-Npyw57g3GsZSxDnsj55:-NpzN7If8e75H0EdJEJF:b-s4c44v) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/d4c172b7a974659e0b3a61e0f8996adbd0c507ef/test-pipeline.yml#L1)):*
> add one more for the reporting
Test outcome is already reported in the build run UI, do we need special reports?
e.g., https://dev.azure.com/anthony-nolan-nova/Atlas/_build/results?buildId=46024&view=ms.vss-test-web.build-test-results-tab

**Pull request merged**
