### PR TITLE
chore: #1: Added categories and pipeline splitted in stages - to resto…

### PR DESCRIPTION
**Pull request by GrigoriyGriban**
chore: #1: Added categories and pipeline split into stages - to restore and build only once, and then run the pre-built tests in parallel

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/8)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/8)* status: all files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @GrigoriyGriban, @pchenery, and @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/8#-NqCxELE6Xz3CxQfiUn3:-NqCxELE6Xz3CxQfiUn4:b-vnhzuj) (no related file):*
Let's see how the run of the pipeline goes, and if ok - we'll merge

___

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/8)* status: all files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @GrigoriyGriban, @pchenery, and @zabeen)

**Review by GrigoriyGriban — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/8)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @daria-sorokina-da, @pchenery, and @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/8#-NqCxELE6Xz3CxQfiUn3:-NqDAUCw7zDVx1dK0VKJ:b-896fix) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's see how the run of the pipeline goes, and if ok - we'll merge
</blockquote></details>

Done.

___

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alikhanmda, @pchenery, and @zabeen)

**Pull request merged**
