### PR TITLE
fix: CBT-2499: Fetch all messages in one trip

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 32 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3D78vy7m0T69u415mA:-O3D78vy7m0T69u415mB:b-1ib4js) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/ce380818b5d53504ac2408f50b57fcda259a65e7/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L32)):*
> ```Smalltalk
> 
>             var lastMessageCount = peekResponse.MessageCount;
>             lastSequenceNumber += lastMessageCount;
> ```

We should start returning the last sequence number in the PeekServiceBusMessagesResponse so that we use FromSequenceNumber = response.LastSequenceNumber + 1 in the batching

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3D7XMs-Xy0Pg0PChto:-O3D7XMs-Xy0Pg0PChtp:by8ofbg) (no related file):*
Requires some changes in Atlas

___

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)* status: all files reviewed, 6 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 20 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y5y4o40_1iW0LLLos:-O3Y5y4o40_1iW0LLLot:beluxg3) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L20)):*
> ```Smalltalk
> 
>         var messages = new List<TMessage>();
>         const int batchSize = 5;
> ```

Let's do 100 for the actual code
___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 21 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y61pd3I5R03NWnERF:-O3Y61pd3I5R03NWnERG:b-ug0kjy) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L21)):*
> ```Smalltalk
>         var messages = new List<TMessage>();
>         const int batchSize = 5;
>         long lastSequenceNumber = -1;
> ```

Let's set the lastSequenceNumber to null in the beginning.
___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 27 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y68EJBo2cSVW3hGqV:-O3Y68EJBo2cSVW3hGqW:b-uma701) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L27)):*
> ```Smalltalk
>             var peekResponse = await peekFunc(new PeekServiceBusMessagesRequest
>             {
>                 FromSequenceNumber = lastSequenceNumber + 1,
> ```

Instead of `lastSequenceNumber + 1` please do `lastSequenceNumber != null ? lastSequenceNumber + 1 : 0`
___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 32 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y6Nwn1Vl-kat58PHN:-O3Y6Nwn1Vl-kat58PHO:b-ccldyz) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L32)):*
> ```Smalltalk
> 
>             var lastMessageCount = peekResponse.MessageCount;
>             lastSequenceNumber = (long)peekResponse.LastSequenceNumber;
> ```

Why do we need to convert the value to long here? Isn't it already long?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)* status: all files reviewed, 6 unresolved discussions (waiting on @pchenery)

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)* status: all files reviewed, 6 unresolved discussions (waiting on @pchenery)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3D7XMs-Xy0Pg0PChto:-O3Y6a5t-Mk5M1hpub-2:b2utrae) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Requires some changes in Atlas
</blockquote></details>

Changes in Atlas done, need some code changes now see comments below

___

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)* status: all files reviewed, 6 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 32 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3D78vy7m0T69u415mA:-O3YB6zh57LwMJt0jr6v:b6iovkl) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/ce380818b5d53504ac2408f50b57fcda259a65e7/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L32)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

We should start returning the last sequence number in the PeekServiceBusMessagesResponse so that we use FromSequenceNumber = response.LastSequenceNumber + 1 in the batching
</blockquote></details>

Sorry, not sure what you mean by this, isn't the last sequence number already in the response?
___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 20 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y5y4o40_1iW0LLLos:-O3Y7GJH1nz9s_0TyiDj:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L20)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's do 100 for the actual code
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 21 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y61pd3I5R03NWnERF:-O3Y7QOG30nuhe87H9AT:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L21)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's set the lastSequenceNumber to null in the beginning.
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 27 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y68EJBo2cSVW3hGqV:-O3Y7bOK-sVQtFeSKObE:bj9r0wp) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L27)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Instead of `lastSequenceNumber + 1` please do `lastSequenceNumber != null ? lastSequenceNumber + 1 : 0`
</blockquote></details>

Done, but have to cast it to long otherwise VS doesn't like it
___
*[`Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs` line 32 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54#-O3Y6Nwn1Vl-kat58PHN:-O3Y9I3o6myN6qYhqdV8:bfw0qto) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/2cb8964484f32198d8704a751908968b882c7ee4/Atlas.Auto.Tests/TestHelpers/Services/MessageFetcher.cs#L32)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Why do we need to convert the value to long here? Isn't it already long?
</blockquote></details>

Done, it gave me an error before, I assume because I didn't have long? lastSequenceNumber

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/54)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
